# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4cc301db80fb36af45c560a2af6339c24a4175adaae0b8c02e6fb7481a3133a662b0bb9164380599e59bd0745f5034df7dc7f3d4936d13b090afd29038546ff

test:
  secret_key_base: c3de525acbb8c062eace25758f4ac36e65b2e3015ab2ea6cbc2be9b335a93207825ab48b939af5f6f65e2daae501791b584ca3e8a01dedd33b8654c6b5242cd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
